linters:
  enable:
  - gofmt
  - goimports
  - errcheck
  - nestif
  - wrapcheck
  - depguard
  - gosimple
  - goconst
  - gomodguard
issues:
  fix: true
  exclude-rules:
  - path: '(.+)_test\.go'
    linters:
    - depguard

linters-settings:
  gosimple:
    go: "1.17"
    checks: ["all"]
  wrapcheck:
    ignorePackageGlobs:
    - github.com/slalombuild/fusion/*
  depguard:
    rules:
      main:
        deny:
        - pkg: 'log'
          desc: 'logging is allowed only by github.com/rs/zerolog/log'
        - pkg: github.com/tj/assert
          desc: 'assert is allowed only by github.com/stretchr/testify/assert'
  gomodguard:
    blocked:
      modules:
      - github.com/tj/assert:
          recommendations:
          - github.com/stretchr/testify/assert
          reason: "testify assert is the preferred testing library for this project"
