builds:
- id: "fusion"
  main: "./cmd/fusion"
  binary: "fusion"
  goos:
  - linux
  - windows
  - darwin
brews:
- name: fusion
  homepage: "https://github.com/slalombuild/fusion"
  description: "Generate secure by default cloud infrastructure configuration with Go and Terraform"
  license: "MIT"
  goarm: "6"
  repository:
    owner: slalombuild
    name: fusion
  url_template: "https://github.com/slalombuild/fusion/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com

scoops:
- name: fusion
  url_template: "https://github.com/slalombuild/fusion/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  repository:
    owner: slalombuild
    name: fusion
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: Others
    order: 999

  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^images:"
    - "^_examples:"
