# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fusion < Formula
  desc "Generate secure by default cloud infrastructure configuration with Go and Terraform"
  homepage "https://github.com/slalombuild/fusion"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slalombuild/fusion/releases/download/v0.2.4/fusion_0.2.4_darwin_amd64.tar.gz"
      sha256 "8d51fe5b1638b7674233fd10c915d2dfe114e2ac452247a02724b8522a54a1a0"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slalombuild/fusion/releases/download/v0.2.4/fusion_0.2.4_darwin_arm64.tar.gz"
      sha256 "15cd5ee37c61fbb9086cb631f120535f2e32a9507726f66b2b5fbbb2343b8c6f"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/slalombuild/fusion/releases/download/v0.2.4/fusion_0.2.4_linux_amd64.tar.gz"
      sha256 "017c8c232543e97eb75dd851e62e894a0cd876050271c8623db781b677a5ad24"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slalombuild/fusion/releases/download/v0.2.4/fusion_0.2.4_linux_arm64.tar.gz"
      sha256 "aab985144beef3904095537c9fee86cc3cd76567df6094e13b8f881631064eb9"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end
end
