# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fusion < Formula
  desc "Generate secure by default cloud infrastructure configuration with Go and Terraform"
  homepage "https://github.com/SlalomBuild/fusion"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.6/fusion_0.1.6_darwin_amd64.tar.gz"
      sha256 "4b7ce6b1c81005f026a85b0415cbdb41d9ae802938b7d54a8c49de15ab5c3e63"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.6/fusion_0.1.6_darwin_arm64.tar.gz"
      sha256 "b0e5f2062bb732bfedf90b0d902381119a570864e99c2525f0da04df4e8ac4e4"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.6/fusion_0.1.6_linux_amd64.tar.gz"
      sha256 "fcc7c8f3fc7a667325c65c5c2eb46e35c5b6e485ecc7b0958c22adbdd82a5d50"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.6/fusion_0.1.6_linux_arm64.tar.gz"
      sha256 "2188f0a1dbe81a72762d45f0471504207e9813374fa70606c58553053c0f7f4b"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end
end
