# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fusion < Formula
  desc "Generate secure by default cloud infrastructure configuration with Go and Terraform"
  homepage "https://github.com/SlalomBuild/fusion"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.5/fusion_0.1.5_darwin_amd64.tar.gz"
      sha256 "d36d5ab62354be6d32dab2ba3ce4f825bce8d0e9ba59340e15ebc3b46f123c4b"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.5/fusion_0.1.5_darwin_arm64.tar.gz"
      sha256 "9779608a02b7d689f26e299f3e4405513bcd8c5f595e3d9fd4148922b1e69d89"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.5/fusion_0.1.5_linux_arm64.tar.gz"
      sha256 "d4affe307ae948dfee9a3c900b97ddc6e023776b570246046b0a522464a50c75"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SlalomBuild/fusion/releases/download/v0.1.5/fusion_0.1.5_linux_amd64.tar.gz"
      sha256 "3ad75e27b7809a08c744e968e9ba14c514d120b894c1d5044c6d354d9ba4fa85"

      def install
        bin.install "fusion"
        bin.install "fusionctl"
      end
    end
  end
end
